TRUNCATE TABLE role;
INSERT INTO  role (id,name) values ('1','ROLE_USER');
INSERT INTO  role (id,name) values ('2','ROLE_ADMIN');

TRUNCATE TABLE country;
INSERT INTO country (id,locale,name) VALUES ( 1,"en","en");
INSERT INTO country (id,locale,name) VALUES ( 2,"ar_AE","ar_AE");
INSERT INTO country (id,locale,name) VALUES ( 3,"ar_JO","ar_JO");
INSERT INTO country (id,locale,name) VALUES ( 4,"hr_HR","hr_HR");
INSERT INTO country (id,locale,name) VALUES ( 5,"fr_BE","fr_BE");
INSERT INTO country (id,locale,name) VALUES ( 6,"kk_KZ","kk_KZ");
INSERT INTO country (id,locale,name) VALUES ( 7,"zh_TW","zh_TW");
INSERT INTO country (id,locale,name) VALUES ( 8,"zh_HK","zh_HK");
INSERT INTO country (id,locale,name) VALUES ( 9,"it","it");
INSERT INTO country (id,locale,name) VALUES ( 10,"en_KW","en_KW");
INSERT INTO country (id,locale,name) VALUES ( 11,"hu_HU","hu_HU");
INSERT INTO country (id,locale,name) VALUES ( 12,"ko","ko");
INSERT INTO country (id,locale,name) VALUES ( 13,"th_TH","th_TH");
INSERT INTO country (id,locale,name) VALUES ( 14,"fi","fi");
INSERT INTO country (id,locale,name) VALUES ( 15,"en_FM","en_FM");
INSERT INTO country (id,locale,name) VALUES ( 16,"et_EE","et_EE");
INSERT INTO country (id,locale,name) VALUES ( 17,"en_EG","en_EG");
INSERT INTO country (id,locale,name) VALUES ( 18,"pt_PT","pt_PT");
INSERT INTO country (id,locale,name) VALUES ( 19,"ar_OM","ar_OM");
INSERT INTO country (id,locale,name) VALUES ( 20,"en_SG","en_SG");
INSERT INTO country (id,locale,name) VALUES ( 21,"ar_BH","ar_BH");
INSERT INTO country (id,locale,name) VALUES ( 22,"pt","pt");
INSERT INTO country (id,locale,name) VALUES ( 23,"ru","ru");
INSERT INTO country (id,locale,name) VALUES ( 24,"en_NZ","en_NZ");
INSERT INTO country (id,locale,name) VALUES ( 25,"ar_SA","ar_SA");
INSERT INTO country (id,locale,name) VALUES ( 26,"de_CH","de_CH");
INSERT INTO country (id,locale,name) VALUES ( 27,"sk","sk");
INSERT INTO country (id,locale,name) VALUES ( 28,"he_IL","he_IL");
INSERT INTO country (id,locale,name) VALUES ( 29,"en_ZA","en_ZA");
INSERT INTO country (id,locale,name) VALUES ( 30,"ru_KZ","ru_KZ");
INSERT INTO country (id,locale,name) VALUES ( 31,"hi","hi");
INSERT INTO country (id,locale,name) VALUES ( 32,"sv","sv");
INSERT INTO country (id,locale,name) VALUES ( 33,"cs","cs");
INSERT INTO country (id,locale,name) VALUES ( 34,"uk_UA","uk_UA");
INSERT INTO country (id,locale,name) VALUES ( 35,"de_AT","de_AT");
INSERT INTO country (id,locale,name) VALUES ( 36,"fr_CH","fr_CH");
INSERT INTO country (id,locale,name) VALUES ( 37,"hu","hu");
INSERT INTO country (id,locale,name) VALUES ( 38,"nl","nl");
INSERT INTO country (id,locale,name) VALUES ( 39,"id","id");
INSERT INTO country (id,locale,name) VALUES ( 40,"vi","vi");
INSERT INTO country (id,locale,name) VALUES ( 41,"fr_CA","fr_CA");
INSERT INTO country (id,locale,name) VALUES ( 42,"lv_LV","lv_LV");
INSERT INTO country (id,locale,name) VALUES ( 43,"ar_EG","ar_EG");
INSERT INTO country (id,locale,name) VALUES ( 44,"ar_KW","ar_KW");
INSERT INTO country (id,locale,name) VALUES ( 45,"en_MY","en_MY");
INSERT INTO country (id,locale,name) VALUES ( 46,"da","da");
INSERT INTO country (id,locale,name) VALUES ( 47,"en_JO","en_JO");
INSERT INTO country (id,locale,name) VALUES ( 48,"cs_CZ","cs_CZ");
INSERT INTO country (id,locale,name) VALUES ( 49,"en_AE","en_AE");
INSERT INTO country (id,locale,name) VALUES ( 50,"es","es");
INSERT INTO country (id,locale,name) VALUES ( 51,"pl_PL","pl_PL");
INSERT INTO country (id,locale,name) VALUES ( 52,"sk_SK","sk_SK");
INSERT INTO country (id,locale,name) VALUES ( 53,"en_HK","en_HK");
INSERT INTO country (id,locale,name) VALUES ( 54,"lt_LT","lt_LT");
INSERT INTO country (id,locale,name) VALUES ( 55,"en_OM","en_OM");
INSERT INTO country (id,locale,name) VALUES ( 56,"en_CA","en_CA");
INSERT INTO country (id,locale,name) VALUES ( 57,"en_PK","en_PK");
INSERT INTO country (id,locale,name) VALUES ( 58,"pl","pl");
INSERT INTO country (id,locale,name) VALUES ( 59,"nl_BE","nl_BE");
INSERT INTO country (id,locale,name) VALUES ( 60,"no","no");
INSERT INTO country (id,locale,name) VALUES ( 61,"es_CO","es_CO");
INSERT INTO country (id,locale,name) VALUES ( 62,"fr","fr");
INSERT INTO country (id,locale,name) VALUES ( 63,"ja","ja");
INSERT INTO country (id,locale,name) VALUES ( 64,"en_SA","en_SA");
INSERT INTO country (id,locale,name) VALUES ( 65,"en_IN","en_IN");
INSERT INTO country (id,locale,name) VALUES ( 66,"de","de");
INSERT INTO country (id,locale,name) VALUES ( 67,"fr_MA","fr_MA");
INSERT INTO country (id,locale,name) VALUES ( 68,"en_BH","en_BH");
INSERT INTO country (id,locale,name) VALUES ( 69,"zh","zh");
INSERT INTO country (id,locale,name) VALUES ( 70,"sl_SI","sl_SI");
INSERT INTO country (id,locale,name) VALUES ( 71,"ro_RO","ro_RO");
INSERT INTO country (id,locale,name) VALUES ( 72,"ca","ca");
INSERT INTO country (id,locale,name) VALUES ( 73,"en_PH","en_PH");
INSERT INTO country (id,locale,name) VALUES ( 74,"en_GB","en_GB");

TRUNCATE TABLE node;
INSERT INTO node (id,name,path) VALUES (1,"Admin","/admin/users");
INSERT INTO node (id,name,parent_node_id,path) VALUES (8,"Subsidiary",1,"/admin/subsidiary");
INSERT INTO node (id,name,parent_node_id,path) VALUES (9,"Site",1,"/admin/site");
INSERT INTO node (id,name,parent_node_id,path) VALUES (10,"Category",1,"/admin/category");
INSERT INTO node (id,name,parent_node_id,path) VALUES (11,"Model",1,"/admin/model");
INSERT INTO node (id,name,parent_node_id,path) VALUES (12,"Variant",1,"/admin/variant");
INSERT INTO node (id,name,parent_node_id,path) VALUES (13,"Price",1,"/admin/price");
INSERT INTO node (id,name,parent_node_id,path) VALUES (14,"Data Source",1,"/admin/datasource");
INSERT INTO node (id,name,parent_node_id,path) VALUES (15,"Data Relation",1,"/admin/dataRelation");
INSERT INTO node (id,name,parent_node_id,path) VALUES (16,"Interface",1,"/admin/interface");
INSERT INTO node (id,name,parent_node_id,path) VALUES (17,"Src & Trg Mapping",1,"/admin/mapping");
INSERT INTO node (id,name,parent_node_id,path) VALUES (18,"Role",1,"/admin/role");
INSERT INTO node (id,name,parent_node_id,path) VALUES (19,"User",1,"/admin/user");
INSERT INTO node (id,name,parent_node_id,path) VALUES (20,"Cronjob",1,"/admin/cronjob");
INSERT INTO node (id,name,parent_node_id,path) VALUES (21,"Media",1,"/admin/media");
INSERT INTO node (id,name,parent_node_id,path) VALUES (22,"Scheduler",1,"/admin/scheduler");
INSERT INTO node (id,name,path) VALUES (2,"Scheduling","/scheduling");
INSERT INTO node (id,name,parent_node_id,path) VALUES (39,"Summary",2,"/schedule/summary");
INSERT INTO node (id,name,parent_node_id,path) VALUES (40,"Out of Stock Report",2,"/schedule/stockReport");
INSERT INTO node (id,name,parent_node_id,path) VALUES (41,"50 Price Report",2,"/schedule/priceReport");
INSERT INTO node (id,name,path) VALUES (3,"Toolkits","/toolkit");
INSERT INTO node (id,name,parent_node_id,path) VALUES (23,"Stock report",3,"/toolkit/stockReport");
INSERT INTO node (id,name,parent_node_id,path) VALUES (24,"Price report",3,"/toolkit/priceReport");
INSERT INTO node (id,name,parent_node_id,path) VALUES (25,"Add-on report",3,"/toolkit/addonReport");
INSERT INTO node (id,name,parent_node_id,path) VALUES (26,"SIM report",3,"/toolkit/smReport");
INSERT INTO node (id,name,parent_node_id,path) VALUES (27,"Trade-in report",3,"/toolkit/tradeinReport");
INSERT INTO node (id,name,parent_node_id,path) VALUES (28,"SC+ report",3,"/toolkit/scplusReport");
INSERT INTO node (id,name,parent_node_id,path) VALUES (29,"EUP report",3,"/toolkit/eupReport");
INSERT INTO node (id,name,parent_node_id,path) VALUES (39,"Gift Report",3,"/toolkit/giftReport");
INSERT INTO node (id,name,parent_node_id,path) VALUES (30,"E-warranty",3,"/toolkit/ewarranty");
INSERT INTO node (id,name,parent_node_id,path) VALUES (31,"Benefits",3,"/toolkit/benefits");
INSERT INTO node (id,name,parent_node_id,path) VALUES (32,"Availability",3,"/toolkit/availability");
INSERT INTO node (id,name,path) VALUES (4,"Finders","/finders");
INSERT INTO node (id,name,path) VALUES (5,"Order monitor","/orders");
INSERT INTO node (id,name,path) VALUES (6,"Quality assurances","/quality");
INSERT INTO node (id,name,parent_node_id,path) VALUES (35,"Checkout",6,"/list");
INSERT INTO node (id,name,parent_node_id,path) VALUES (36,"Tariff",6,"/tariff");
INSERT INTO node (id,name,parent_node_id,path) VALUES (37,"Compare json",6,"/comparejson");
INSERT INTO node (id,name,parent_node_id,path) VALUES (38,"Compare excel",6,"/compareexcel");
INSERT INTO node (id,name,path) VALUES (7,"Generator","/generator");